---
apiVersion: v1
kind: Secret
metadata:
  name: "cloud-credentials"
  namespace: {{ include "oadp-operator.namespace" . }}
  labels:
    openshift-adp.dataprotectionapplication: {{ .Values.global.resourceNamePrefix }}
    openshift.io/oadp: "true"
    {{ include "oadp-operator.gitopsLabels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
type: Opaque
data:
  cloud: |
    {{ .Files.Get "configs/s3-credentials" | b64enc | indent 4 }} 
---
