---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ include "oadp-operator.namespace" . }}
  namespace: {{ include "oadp-operator.namespace" . }}
  annotations:
    argocd.argoproj.io/sync-wave: '1'
  labels:
    {{ include "oadp-operator.gitopsLabels" . | nindent 4 }}
spec:
  targetNamespaces:
  - {{ include "oadp-operator.namespace" . }}
