---
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: apps-dr-app2
  # namespace: ${NAMESPACE}
parameters:
- name: NAMESPACE
  displayName: Namespace
  value: web-app2
objects:
- apiVersion: v1
  kind: Namespace
  metadata:
    name: ${NAMESPACE}
  spec: {}
- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: web-app2
    namespace: ${NAMESPACE}
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    storageClassName: gp3-csi
    volumeMode: Filesystem
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: web-app2
    name: web-app2
    namespace: ${NAMESPACE}
  spec:
    replicas: 1
    selector:
      app: web-app2
    strategy:
      resources: {}
    template:
      metadata:
        labels:
          app: web-app2
      spec:
        containers:
        - name: web-app2
          ports:
            - containerPort: 8080
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: VOL_MOUNT_PATH
            value: /oadp/data
          command:
            - /bin/sh
            - -c
            - |
              
              for i in {1..10}; 
              do
                dd if=/dev/urandom of=${VOL_MOUNT_PATH}/${POD_NAME}_oadp-random_${i}.log bs=1024 count=30240;
              done

              while true; 
              do 
                DATA_DIR=${VOL_MOUNT_PATH}/$(date +"%Y%m%d%H")_POD_${POD_NAME}_NODE_${NODE_NAME};
                mkdir -p ${DATA_DIR};
                output="$(date +"%Y-%m-%d_%H-%M-%S-%3N")"; 
                file_name="oadp-$(date +"%m%d%Y-T%H%M").log";
                echo "Current Timestamp: ${output}";
                echo "Written on: ${output}" >> ${DATA_DIR}/${file_name};
                sleep 1; 
              done
          image: image-registry.openshift-image-registry.svc:5000/openshift/nginx:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - mountPath: /oadp/data
            name: web-app2
        volumes:
        - name: web-app2
          persistentVolumeClaim:
            claimName: web-app2
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: web-app2
    name: web-app2
    namespace: ${NAMESPACE}
  spec:
    ports:
    - port: 8080
      targetPort: 8080
    selector:
      app: web-app2
    type: LoadBalancer
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: web-app2
    namespace: ${NAMESPACE}
    labels:
      app: web-app2
      service: web-app2
  spec:
    to:
      kind: Service
      name: web-app2
    port:
      targetPort: 8080
labels:
  app.kubernetes.io/part-of: apps-br-demo
